openapi: 3.0.3
info:
  title: ToDo List API
  version: 1.0.0
  description: ToDo List API
paths:
  /api/todos:
    get:
      operationId: todos_list
      parameters:
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      - name: ordering
        required: false
        in: query
        description: Which field to use when ordering the results.
        schema:
          type: string
      - name: search
        required: false
        in: query
        description: A search term.
        schema:
          type: string
      - in: query
        name: status
        schema:
          type: string
          enum:
          - CONCLUDED
          - IN_PROGRESS
        description: |-
          * `IN_PROGRESS` - in progress
          * `CONCLUDED` - concluded
      tags:
      - todos
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedToDoList'
          description: ''
    post:
      operationId: todos_create
      tags:
      - todos
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ToDo'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ToDo'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ToDo'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ToDo'
          description: ''
  /api/todos/{id}:
    get:
      operationId: todos_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this ToDo.
        required: true
      tags:
      - todos
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ToDo'
          description: ''
    put:
      operationId: todos_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this ToDo.
        required: true
      tags:
      - todos
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ToDo'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ToDo'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ToDo'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ToDo'
          description: ''
    patch:
      operationId: todos_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this ToDo.
        required: true
      tags:
      - todos
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedToDo'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedToDo'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedToDo'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ToDo'
          description: ''
    delete:
      operationId: todos_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this ToDo.
        required: true
      tags:
      - todos
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
components:
  schemas:
    PaginatedToDoList:
      type: object
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=400&limit=100
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=200&limit=100
        results:
          type: array
          items:
            $ref: '#/components/schemas/ToDo'
    PatchedToDo:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        status_display:
          type: string
          readOnly: true
        status:
          type: string
          writeOnly: true
          description: Status of the ToDo (IN_PROGRESS by default)
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        title:
          type: string
          maxLength: 120
        description:
          type: string
          nullable: true
    ToDo:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        status_display:
          type: string
          readOnly: true
        status:
          type: string
          writeOnly: true
          description: Status of the ToDo (IN_PROGRESS by default)
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        title:
          type: string
          maxLength: 120
        description:
          type: string
          nullable: true
      required:
      - created_at
      - id
      - status_display
      - title
      - updated_at
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
